version: '3.8'

services:
  postgres:
    container_name: eteg-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: eteg
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
  app:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    container_name: eteg-api
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/app/src
    env_file:
      - ./backend/.env